logging:
  level:
    root: INFO
    '[io.r2dbc.postgresql.QUERY]': DEBUG # log the queries
    '[io.r2dbc.postgresql.PARAM]': DEBUG # log the parameters

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/teccse_reactive
    username: teccse
    password: teccse

afklm:
  security:
    public-endpoints: >
      /stations/*,
      /faa/*

server:
  reactive:
    session:
      cookie:
        name: JSESSIONID
# the following section requires ss4h reactive
#afklm:
#  security:
#    roles:
#      P_ADMIN:
#        - ADMIN
#        - MODIF
#      P_USER_EMPTY:
#      P_USER:
#        - CONSULT
