logging:
  level:
    root: INFO
    '[io.r2dbc.postgresql.QUERY]': DEBUG # log the queries
    '[io.r2dbc.postgresql.PARAM]': DEBUG # log the parameters

spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  reactive:
    session:
      cookie:
        name: JSESSIONID
